title: "Your Name"
description: "My GitHub profile"
theme: minima

markdown: kramdown
permalink: pretty

header_pages: []
 

# Tell Jekyll to process these files even though they don't start with front matter
include:
  - index.md
  - README_EN.md
  - commissions/cardBadge.md
  - commissions/pulexStickerBase.md

# Don't build these into the site
exclude:
  - README.md